exec-once = $execPrefix fcitx5
exec-once = $execPrefix swaync
exec-once = $execPrefix waybar

exec-once=[workspace 5 silent] $execPrefix Telegram
exec-once=[workspace 5 silent] $execPrefix clash-verge
exec-once=[workspace 5 silent] $execPrefix wechat
