workspace = special:special, gapsin:30, gapsout:60
workspace = special:special, on-created-empty:foot

windowrule = norounding,                                onworkspace:s[true]
windowrule = bordersize 8,                              onworkspace:s[true]
windowrule = opacity 0.8 0.4 1.0,                       onworkspace:s[true]
windowrule = bordercolor rgba(ffffffff) rgba(000000dd), onworkspace:s[true]

windowrule = float, center, class:^(pcmanfm|pavucontrol|blueman-manager|mpv|imv)$
windowrule = workspace 1, class:^(firefox)$
